---
title: "Income_Distribution_test"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
##LOAD our package
library(pridr)


#Other packages
library(ggplot2)
library(ggsci)
library(parallel)
library(tidyr)
library(dplyr)
library(data.table)
library(assertthat)


#Basic format for figs (optional)
scheme_basic <- theme_bw() +
  theme(legend.text = element_text(size = 15)) +
  theme(legend.title = element_text(size = 15)) +
  theme(axis.text = element_text(size = 18)) +
  theme(axis.title = element_text(size = 18, face = "bold")) +
  theme(plot.title = element_text(size = 15, face = "bold", vjust = 1)) +
  theme(plot.subtitle = element_text(size = 9, face = "bold", vjust = 1))+ 
  theme(strip.text = element_text(size = 7))+
  theme(strip.text.x = element_text(size = 18, face = "bold"))+
  theme(strip.text.y = element_text(size = 15, face = "bold"))+
  theme(legend.position = "bottom")+
  theme(legend.text = element_text(size = 12))+
  theme(legend.title = element_text(size = 12,color = "black",face="bold"))+
  theme(axis.text.x= element_text(hjust=1))+
  theme(legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))
```

### Load a sample dataset

```{r cars}

read.csv("Input_Data/Wider_aggregated_deciles.csv", stringsAsFactors = FALSE) %>%
  select(country, year, gdp_ppp_pc_usd2011, gini) %>%
  distinct() %>%
  mutate(sce="Historical data") %>% 
  filter(year > 2013)->data_for_lognorm
head(data_for_lognorm)
```

## 1. Generate deciles using lognormal approach
```{r pressure, echo=FALSE}
start_time= Sys.time()
compute_deciles_lognormal(data_for_lognorm)->lognormal_model

head(lognormal_model)
end_time=Sys.time()

print(paste0("Processed in ",as.integer(end_time-start_time), " seconds"))
```

## 2. Generate lognormal density dist
```{r}

density_dist_1 <- compute_lognormal_dist(mean_income = 15,gini=0.6) %>% mutate(gini=as.character(0.6))
density_dist_2 <- compute_lognormal_dist(mean_income = 15,gini=0.3)%>% mutate(gini=as.character(0.3))
density_dist_3 <- compute_lognormal_dist(mean_income = 15,gini=0.2)%>% mutate(gini=as.character(0.2))

g <- ggplot(data=bind_rows(density_dist_3,density_dist_2,density_dist_1), aes(x=gdp_pcap,y=density,color=gini))+
     geom_line()+scale_color_aaas()

g+scheme_basic

```

### Compile data
```{r}

IV_data <- compile_independent_variables() %>% mutate(Component1_act= Component1, Component2_act= Component2)


Final_historical_data <- read.csv("Input_Data/Final_Historical_data_ISO.csv", stringsAsFactors = FALSE) %>%
   select(year,gini=output_name,iso,country) %>%
   distinct() %>%
   left_join(IV_data %>% select(-gini,-country), by= c("iso","year")) %>%
   mutate(sce= "Historical data") %>%
   select(country,year,iso,sce,gini,labsh,lagged_ninth_decile,lagged_palma_ratio) %>%
   group_by(iso,sce) %>%
   mutate(labsh = ifelse(is.na(labsh),approx_fun(year,labsh,rule = 2),labsh),
          lagged_ninth_decile = ifelse(is.na(lagged_ninth_decile),approx_fun(year,lagged_ninth_decile,rule = 2),lagged_ninth_decile),
          lagged_palma_ratio=ifelse(is.na(lagged_palma_ratio),approx_fun(year,lagged_palma_ratio,rule=2),lagged_palma_ratio)) %>%
   ungroup() %>%
  group_by(year) %>%
  arrange(gini) %>%
   mutate(labsh = ifelse(is.na(labsh),0,labsh),
          lagged_ninth_decile =ifelse(is.na(lagged_ninth_decile),0,lagged_ninth_decile),
          lagged_palma_ratio=ifelse(is.na(lagged_palma_ratio),0,lagged_palma_ratio)) %>%
  ungroup() %>%
   distinct() %>%
   na.omit()


Final_historical_data %>% filter(iso %in% c("ind","chn","usa"))->sample_data

head(sample_data)

```
## 3. Run PC model
```{r}
start_time <- Sys.time()
PC_model_results <- PC_model(sample_data)
head(PC_model_results)

print(paste0("Completed in ", as.integer(Sys.time()-start_time), " seconds."))
```
## Plot deciles
```{r}
g <- ggplot(data=PC_model_results %>% filter(year==2010),aes(x=factor(Category,levels =c('d1','d2','d3','d4',
  'd5','d6','d7','d8',                                                                                'd9','d10')),y=pred_shares,color=country,group=country))+
     geom_line()+
     geom_point()+scale_color_aaas()+xlab("Deciles")

g+scheme_basic
    
```
## 4. Generate GINI for a given set of deciles
```{r}
gini_data <-compute_gini_deciles(PC_model_results %>% mutate(category=Category), inc_col = "pred_shares",grouping_variables = c("country","year"))
head(gini_data)
```
## 5. Aggregate deciles to a region

```{r}
read.csv("Input_Data/Wider_aggregated_deciles.csv", stringsAsFactors = FALSE) %>%
  select(country, year, gdp_ppp_pc_usd2011, population,Income..net.,Category) %>% filter(year%in% c(2015)) %>% mutate(GCAM_region_ID="Global")->ISO_data

head(ISO_data)
```


```{r}
aggregate_country_deciles_to_regions(ISO_data,grouping_variables = c("GCAM_region_ID","year"))->agg_data
head(agg_data)
```



```{r}
g <- ggplot(data=agg_data,aes(x=factor(category,levels =c('d1','d2','d3','d4',
  'd5','d6','d7','d8',                                                                                'd9','d10')),y=shares,group=GCAM_region_ID))+
     geom_line()+
     geom_point()+scale_color_aaas()+xlab("Deciles")+facet_wrap(~year)

g+scheme_basic
```


## 6. Model inter-operability


```{r}
library(ambrosia)

PC_model_results %>% 
  filter(country=="India",year==2010) %>% 
  mutate(gpp_pc = (5000*1000000*pred_shares)/100000,
         Ps=0.6,
         Pn=1.2)->data_for_food_model

head(data_for_food_model)

```

```{r}
food_demand <- food.dmnd(data_for_food_model$Ps,data_for_food_model$Pn,data_for_food_model$gpp_pc/1000)

food_demand$gdp_pc <- data_for_food_model$gpp_pc/1000
food_demand$Category <- data_for_food_model$Category
head(food_demand)
```
```{r}
g <- ggplot(data=food_demand %>% mutate(id="A"), aes(x=gdp_pc,y=Qs+Qn,color=Category,group=id))+
     geom_point(size=3)+scale_color_aaas()+geom_line(color="grey")

g+scheme_basic
```






## 7. Generate results using single component
```{r}
get_deciles_from_components(PC_model_results,use_second_comp = FALSE,grouping_variables = c("country","year"))->Single_comp_results

head(Single_comp_results)
```

